# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7236ed23275beeb787ed0317b52dac1c8febffb0743c1d0e6e3a760e1802d96ba96ef8f8027dc6ad86954a08663c25be2e664dff24a70032ce45e27bed14b433

test:
  secret_key_base: d311aa8e688e330b5105fe4d5cacf7302d091f8ce44939724a3ca9738b07bbee6f802b3e699c4a8f1295ecb346d8298bbcb1d46264e0b9bcb449c91fb1b56ff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
